export const Places = [
  {
    continent: "Africa",
    country_name: [
      "Botswana",
      "Egypt",
      "Kenya",
      "Mauritis",
      "Morocco",
      "Mozambique",
      "Namibia",
      "Seychelles",
      "South Africa",
      "Tanzania",
      "Uganda",
      "Zimbabwe",
    ],
  },
  {
    continent: "Asia",
    country_name: [
      "Cambodia",
      "China",
      "Hong Kong",
      "India",
      "Indonesia",
      "Japan",
      "Maldives",
      "Singapore",
      "Sri Lanka",
      "Thailand",
      "Vietnam",
    ],
  },
  {
    continent: "The Caribbean",
    country_name: [
      "Aruba",
      "Bahamas",
      "British Virgin Islands",
      "Cuba",
      "Dominican Republic",
      "Jamaica",
    ],
  },
  {
    continent: "Europe",
    country_name: [
      "Austria",
      "Belgium",
      "Croatia",
      "Czech Republic",
      "Denmark",
      "England",
      "France",
      "Germany",
      "Greece",
      "Hungary",
      "Iceland",
      "Ireland",
      "Italy",
      "Macedonia",
      "Malta",
      "Netherlands",
      "Poland",
      "Portugal",
      "Serbia",
      "Slovakia",
      "Spain",
      "Sweden",
      "Switzerland",
    ],
  },
  {
    continent: "The Middle East",
    country_name: ["Egypt", "Jordan", "Turkey", "Cuba", "United Arab Emirates"],
  },
  {
    continent: "North America",
    country_name: ["Canada", "Mexico", "Puerto Rico", "USA"],
  },
  {
    continent: "Oceania",
    country_name: [
      "Australia",
      "French Polynesia",
      "Papua New Guinea",
      "New Zealand",
    ],
  },
  {
    continent: "South America",
    country_name: [
      "Argentina",
      "Bolivia",
      "Brazil",
      "Chile",
      "Colombia",
      "Ecuador",
      "Peru",
    ],
  },
];
